# Generated by Django 5.0 on 2024-04-18 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('reference_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BenchmarkSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(default='Untitled Section', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('parent_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compliance.benchmarksection')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.policy')),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_number', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('expected_value', models.TextField()),
                ('rationale', models.TextField(blank=True)),
                ('title', models.CharField(default='Untitled Check', max_length=255)),
                ('audit', models.TextField(blank=True)),
                ('remediation', models.TextField(blank=True)),
                ('impact', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='compliance.benchmarksection')),
            ],
        ),
    ]
